##### General ############################################################

set -g base-index 1          # Number windows from 1, like Vim
set -g history-limit 1048576 # More lines of scrollback
set -g mode-keys vi          # Vi mode for copy-mode (prefix-[)
set -g focus-events on       # Enable focus events
set -g mouse on              # Use mouse keybindings
set -g prefix2 M-a           # Use Alt-A as additional prefix key, besides ^B
set -g repeat-time 200

##### Terminal ###########################################################

set -g default-terminal "tmux-256color"         # Set $TERM under tmux
set -sa terminal-features ",xterm-256color:RGB" # TrueColor support

set -g set-titles             # Enable title setting
set -g set-titles-string "#T" # Show program title as window title

##### Clipboard ##########################################################

set -sg set-clipboard on # Use OSC 52 clipboard integration (no copy-pipe)

##### UI #################################################################

set -g status off                    # Disable status line by default
set -g status-style fg=blue,bg=black # Non-distracting status bar colors

##### Timing #############################################################

set -sg escape-time 0 # Disable delay of 500ms for `Esc` in tmux
set -g repeat-time 150 # Set prefix repeat timeout to 150ms

##### Copy Mode ##########################################################

bind -T prefix Escape copy-mode       # Enter copy-mode on `prefix-Esc`
bind -T copy-mode-vi i send -X cancel # `i` exits copy-mode (same as default keybinding `q`)

# `y` copies selection to system clipboard
bind -T copy-mode-vi y send -X copy-pipe-and-cancel

# Select region using `^v`, the same way as in Vim
bind -T copy-mode-vi C-v send -X rectangle-toggle

##### Mouse ##############################################################

# Double-click selects a word without copying or leaving copy-mode.
bind -T copy-mode-vi DoubleClick1Pane \
  select-pane \; \
  send -X select-word
bind -T root DoubleClick1Pane \
  select-pane -t = \; \
  if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" \
    { send-keys -M } \
    { copy-mode -H ; send-keys -X select-word }

# Triple-click selects a line without copying or leaving copy-mode.
bind -T copy-mode-vi TripleClick1Pane \
  select-pane \; \
  send -X select-line
bind -T root TripleClick1Pane \
  select-pane -t = \; \
  if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" \
    { send-keys -M } \
    { copy-mode -H ; send-keys -X select-line }


unbind -T copy-mode-vi MouseDragEnd1Pane # Keep copy-mode active after finishing a mouse drag.
unbind -T root MouseDown3Pane            # Disable popup menu on `RightClick`
unbind -T root M-MouseDown3Pane          # Disable popup menu on `M-RightClick`
