# Rendering backend
backend = "glx";

# Disable fading to avoid flicker on window open/close
fading = false;
no-fading-openclose = true;

# Disable shadows
shadow = false;

# Don't dim inactive windows
inactive-dim = 0;

# Fix screen tearing
vsync = true;
