
[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 12.0

[font.normal]
family = "IosevkaFixed Nerd Font"
style = "Regular"

[general]
live_config_reload = false

import = [
  "~/.config/alacritty/bindings.toml",
  "~/.config/alacritty/colorscheme.toml",
]
