live_config_reload = false

import = [
  "~/.config/alacritty/bindings.toml",
  "~/.config/alacritty/colorscheme.toml",
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 11.0

[font.normal]
family = "IosevkaFixed Nerd Font"
style = "Regular"
