[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x5c6a72"
blue = "0x3a94c5"
cyan = "0x35a77c"
green = "0x8da101"
magenta = "0xdf69ba"
red = "0xf85552"
white = "0xe0dcc7"
yellow = "0xdfa000"

[colors.cursor]
cursor = "0xcccccc"
text = "0x111111"

[colors.normal]
black = "0x5c6a72"
blue = "0x3a94c5"
cyan = "0x35a77c"
green = "0x8da101"
magenta = "0xdf69ba"
red = "0xf85552"
white = "0xe0dcc7"
yellow = "0xdfa000"

[colors.primary]
background = "0xfdf6e3"
foreground = "0x5c6a72"
